version: "3.9"

services:
  gateway:
    build:
      context: .
      dockerfile: Src/BudgetTracker.Gateway/Dockerfile
      args:
        NUGET_PAT: ${NUGET_PAT}
        GOOGLE_CLOUD_PROJECT_ID: <project-id>
        GOOGLE_APPLICATION_CREDENTIALS: /gcp/credentials.json        
    image: budget-tracker-gateway
    ports:
      - "3000:3000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # Downstream__Api1: http://budget-tracker-finance:3001
      # ReverseProxy__Clusters__finance-cluster__Destinations__instance-01__Address: http://budget-tracker-finance:3001
      ENV: Development
      API_KEY: <api-key>
      YARP_API_KEY: <yarp-api-key>
    volumes:
      - /Volumes/SecureDisk/budget-tracker-453204-64c2649cc266.json:/gcp/credentials.json:ro
    depends_on:
      - budget-tracker-finance

  budget-tracker-finance:
    build:
      context: .      
      dockerfile: Src/BudgetTracker.Finance/Dockerfile
      args:
        NUGET_PAT: ${NUGET_PAT}    
    image: budget-tracker-finance
    ports:
      - "3001:3001"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ENV: Development
      YARP_API_KEY: <yarp-api-key>
      POSTGRES_HOST: host.docker.internal
      POSTGRES_DATABASE: BudgetTracker.Finance
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_WRITE_PORT: 5432
      GOOGLE_CLOUD_PROJECT_ID: <project-id>
      PUB_SUB_TOPIC: <sub-name>
