name: budget-tracker
version: "3.9"

services:
    gateway:
        build:
            dockerfile: Src/BudgetTracker.Gateway/Dockerfile
            target: dev
            args:
                NUGET_PAT: ${NUGET_PAT}
                APP_ENV: Development
        image: budget-tracker-gateway
        ports:
            - "3000:3000"
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ReverseProxy__Clusters__finance-cluster__Destinations__instance-01__Address: http://finance:3001
            ENV: Development
            PORT: 3000
        volumes:
            - type: bind
              source: /Volumes/SecureDisk/Budget-Tracker/gateway-local-secrets.json
              target: /secrets/gateway-secrets.json
              read_only: true
            - type: bind
              source: .
              target: /budget-tracker
              
            - /budget-tracker/Src/BudgetTracker.Gateway/bin/
            - /budget-tracker/Src/BudgetTracker.Gateway/obj/
            - /budget-tracker/Src/BudgetTracker.Shared/bin/
            - /budget-tracker/Src/BudgetTracker.Shared/obj/
    
    finance:
        build:
            dockerfile: Src/BudgetTracker.Finance/Dockerfile
            target: dev
            args:
                NUGET_PAT: ${NUGET_PAT}
                APP_ENV: Development
        image: budget-tracker-finance
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ENV: Development
            Postgres__Write__Host: host.docker.internal # <-- host.docker.internal = computer's localhost
            Postgres__Read__Host: host.docker.internal
            Postgres__Migrate__Host: host.docker.internal
            PORT: 3001
            GOOGLE_APPLICATION_CREDENTIALS: /gcp/credentials.json
        volumes:
            - type: bind
              source: /Volumes/SecureDisk/Budget-Tracker/bt-gcp-credentials.json
              target: /gcp/credentials.json
              read_only: true
            - type: bind
              source: /Volumes/SecureDisk/Budget-Tracker/finance-local-secrets.json
              target: /secrets/finance-secrets.json
              read_only: true
            - type: bind
              source: .
              target: /budget-tracker
              
            - /budget-tracker/Src/BudgetTracker.Finance/bin/
            - /budget-tracker/Src/BudgetTracker.Finance/obj/            
            - /budget-tracker/Src/BudgetTracker.Shared/bin/
            - /budget-tracker/Src/BudgetTracker.Shared/obj/