<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <RootNameSpace>BudgetTracker.Gateway</RootNameSpace>
    </PropertyGroup>

    <ItemGroup>
<!--        <PackageReference Include="Google.Cloud.Diagnostics.AspNetCore" />-->
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="OpenTelemetry.Exporter.Console" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
        <PackageReference Include="Yarp.ReverseProxy" />
        <PackageReference Include="Abhiram.Extensions.DotEnv" />
        <PackageReference Include="Abhiram.Abstractions.Logging" />
        <PackageReference Include="Abhiram.Secrets.Providers" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BudgetTracker.Shared\BudgetTracker.Shared.csproj" />
      <ProjectReference Include="..\BudgetTracker.Warehouse\BudgetTracker.Warehouse.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Services\" />
    </ItemGroup>

</Project>
