// <auto-generated />
using System;
using BudgetTracker.Finance.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetTracker.Finance.Infrastructure.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20251122091600_InitialSetup")]
    partial class InitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetTracker.Finance.Domain.Entities.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.HasKey("Id");

                    b.ToTable("banks");
                });

            modelBuilder.Entity("BudgetTracker.Finance.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("BudgetTracker.Finance.Domain.Entities.Due", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comments")
                        .HasComment("Comments to describe each update action on due")
                        .HasAnnotation("Relational:JsonPropertyName", "comments");

                    b.Property<string>("CompletedDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("completed_date")
                        .HasAnnotation("Relational:JsonPropertyName", "completed_date");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Creditor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creditor")
                        .HasComment("Money is owed to this person")
                        .HasAnnotation("Relational:JsonPropertyName", "creditor");

                    b.Property<string>("Debtor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debtor")
                        .HasComment("Person who owes money.")
                        .HasAnnotation("Relational:JsonPropertyName", "debtor");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComment("Description of what the Due is")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("DueAmount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("due_amount")
                        .HasComment("Leftover due amount")
                        .HasAnnotation("Relational:JsonPropertyName", "due_amount");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remarks")
                        .HasComment("Additional info apert from description to describe the payment of the dues")
                        .HasAnnotation("Relational:JsonPropertyName", "remarks");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("start_date")
                        .HasAnnotation("Relational:JsonPropertyName", "start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title")
                        .HasComment("Due short title")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<string>("TotalAmount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("total_amount")
                        .HasComment("Total amount due to Creditor")
                        .HasAnnotation("Relational:JsonPropertyName", "total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.HasKey("Id");

                    b.ToTable("dues");
                });

            modelBuilder.Entity("BudgetTracker.Finance.Domain.Entities.MonthlyInstallment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comments")
                        .HasComment("Comments to describe each update action on Installment")
                        .HasAnnotation("Relational:JsonPropertyName", "comments");

                    b.Property<int>("Completed")
                        .HasColumnType("integer")
                        .HasColumnName("completed")
                        .HasComment("Leftover number of monthly installments")
                        .HasAnnotation("Relational:JsonPropertyName", "completed");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("end_date")
                        .HasAnnotation("Relational:JsonPropertyName", "end_date");

                    b.Property<string>("InstallmentAmount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("installment_amount")
                        .HasComment("Amount to be paid at each installment")
                        .HasAnnotation("Relational:JsonPropertyName", "installment_amount");

                    b.Property<int>("Installments")
                        .HasColumnType("integer")
                        .HasColumnName("installments")
                        .HasComment("Total number of monthly installments")
                        .HasAnnotation("Relational:JsonPropertyName", "installments");

                    b.Property<string>("PrincipleAmount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("principle_amount")
                        .HasComment("Total amount to be paid")
                        .HasAnnotation("Relational:JsonPropertyName", "principle_amount");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remarks")
                        .HasComment("Additional info apert from description to describe the payment of the Installment")
                        .HasAnnotation("Relational:JsonPropertyName", "remarks");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("start_date")
                        .HasAnnotation("Relational:JsonPropertyName", "start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.HasKey("Id");

                    b.ToTable("monthly_installments");
                });

            modelBuilder.Entity("BudgetTracker.Finance.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("actual_amount")
                        .HasComment("Amount that was used in a transaction and left the bank account. Credit card transaction amounts won't be added in actual amount")
                        .HasAnnotation("Relational:JsonPropertyName", "actual_amount");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount")
                        .HasComment("Amount that was used in a transaction")
                        .HasAnnotation("Relational:JsonPropertyName", "amount");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id")
                        .HasAnnotation("Relational:JsonPropertyName", "category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date")
                        .HasAnnotation("Relational:JsonPropertyName", "date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<int>("FromBank")
                        .HasColumnType("integer")
                        .HasColumnName("from_bank")
                        .HasAnnotation("Relational:JsonPropertyName", "from_bank");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tags")
                        .HasAnnotation("Relational:JsonPropertyName", "tags");

                    b.Property<int>("ToBank")
                        .HasColumnType("integer")
                        .HasColumnName("to_bank")
                        .HasAnnotation("Relational:JsonPropertyName", "to_bank");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FromBank");

                    b.HasIndex("ToBank");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("BudgetTracker.Finance.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("BudgetTracker.Finance.Domain.Entities.Category", "CategoryF")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetTracker.Finance.Domain.Entities.Bank", "FromBankF")
                        .WithMany()
                        .HasForeignKey("FromBank")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetTracker.Finance.Domain.Entities.Bank", "ToBankF")
                        .WithMany()
                        .HasForeignKey("ToBank")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryF");

                    b.Navigation("FromBankF");

                    b.Navigation("ToBankF");
                });
#pragma warning restore 612, 618
        }
    }
}
