// <auto-generated />
using System;
using BudgetTracker.Finance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetTracker.Finance.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20260329075656_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetTracker.Finance.Entities.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("created_at")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date")
                        .HasColumnName("updated_at")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.HasKey("Id");

                    b.ToTable("banks");
                });

            modelBuilder.Entity("BudgetTracker.Finance.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("created_at")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date")
                        .HasColumnName("updated_at")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("BudgetTracker.Finance.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("actual_amount")
                        .HasComment("Amount that will be used in a transaction and left the bank account. Credit card transaction amounts won't be added in actual amount")
                        .HasAnnotation("Relational:JsonPropertyName", "actual_amount");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount")
                        .HasComment("Amount that will be used in a transaction")
                        .HasAnnotation("Relational:JsonPropertyName", "amount");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id")
                        .HasAnnotation("Relational:JsonPropertyName", "category_id");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("created_at")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date")
                        .HasAnnotation("Relational:JsonPropertyName", "date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("description")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<int?>("FromBank")
                        .HasColumnType("integer")
                        .HasColumnName("from_bank")
                        .HasAnnotation("Relational:JsonPropertyName", "from_bank");

                    b.Property<int?>("ToBank")
                        .HasColumnType("integer")
                        .HasColumnName("to_bank")
                        .HasAnnotation("Relational:JsonPropertyName", "to_bank");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date")
                        .HasColumnName("updated_at")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FromBank");

                    b.HasIndex("ToBank");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transaction_Actual_Amount", "(actual_amount IS NULL) OR (actual_amount >= 0.01 AND actual_amount <= 1000000)");

                            t.HasCheckConstraint("CK_Transaction_Amount", "amount >= 0.01 AND amount <= 1000000");

                            t.HasCheckConstraint("CK_Transaction_Description_Regex", "description ~ '^[a-zA-Z0-9# ,]*$'");

                            t.HasCheckConstraint("CK_Transactions_Bank", "(type = 1 AND from_bank IS NOT NULL) OR (type = 2 AND to_bank IS NOT NULL)");

                            t.HasCheckConstraint("CK_Transactions_Description_MinLength", "LENGTH(TRIM(description)) >= 3");

                            t.HasCheckConstraint("CK_Transactions_Type", "type = 1 OR type = 2");
                        });
                });

            modelBuilder.Entity("BudgetTracker.Finance.Entities.TransactionsMeta", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id")
                        .HasAnnotation("Relational:JsonPropertyName", "transaction_id");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("created_at")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<int?>("DueId")
                        .HasColumnType("integer")
                        .HasColumnName("due_id")
                        .HasAnnotation("Relational:JsonPropertyName", "due_id");

                    b.Property<int?>("EmiId")
                        .HasColumnType("integer")
                        .HasColumnName("emi_id")
                        .HasAnnotation("Relational:JsonPropertyName", "emi_id");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags")
                        .HasAnnotation("Relational:JsonPropertyName", "tags");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date")
                        .HasColumnName("updated_at")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.HasKey("TransactionId");

                    b.ToTable("transactions_meta");
                });

            modelBuilder.Entity("BudgetTracker.Finance.Entities.Transaction", b =>
                {
                    b.HasOne("BudgetTracker.Finance.Entities.Category", "CategoryF")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetTracker.Finance.Entities.Bank", "FromBankF")
                        .WithMany()
                        .HasForeignKey("FromBank");

                    b.HasOne("BudgetTracker.Finance.Entities.Bank", "ToBankF")
                        .WithMany()
                        .HasForeignKey("ToBank");

                    b.Navigation("CategoryF");

                    b.Navigation("FromBankF");

                    b.Navigation("ToBankF");
                });

            modelBuilder.Entity("BudgetTracker.Finance.Entities.TransactionsMeta", b =>
                {
                    b.HasOne("BudgetTracker.Finance.Entities.Transaction", "TransactionF")
                        .WithOne("Meta")
                        .HasForeignKey("BudgetTracker.Finance.Entities.TransactionsMeta", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionF");
                });

            modelBuilder.Entity("BudgetTracker.Finance.Entities.Transaction", b =>
                {
                    b.Navigation("Meta")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
