steps:
  # Step 1: Build the Docker image and pass NUGET_PAT as build arg
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Docker Build'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - '$_LOCATION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY/$_IMAGE:latest'
      - '-f'
      - 'Src/BudgetTracker.Finance/Dockerfile'
      - '--build-arg'
      - 'NUGET_PAT=$_NUGET_PAT'
      - '--build-arg'
      - 'APP_ENV=GoogleCloud'
      - '.'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Docker Push'
    args: ['push', '$_LOCATION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY/$_IMAGE:latest']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'Deploy to Cloud run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'budget-tracker-finance'
      - '--image'
      - '$_LOCATION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY/$_IMAGE:latest'
      - '--region'
      - '$_LOCATION'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--ingress=internal'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT_ID=$_PROJECT_ID'
      - '--set-env-vars'
      - 'ASPNETCORE_ENVIRONMENT=GoogleCloud'
      - '--set-env-vars'
      - 'JWT__AUDIENCE=$_AUDIENCE'
      - '--set-env-vars'
      - 'JWT__ISSUER=https://accounts.google.com'

# Optional: declare the image for metadata
images:
    - '$_LOCATION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY/$_IMAGE:latest'

options:
    logging: CLOUD_LOGGING_ONLY