<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <RootNameSpace>BudgetTracker.Warehouse</RootNameSpace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Cloud.BigQuery.V2" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
        <PackageReference Include="Abhiram.Extensions.DotEnv" />
        <PackageReference Include="Google.Cloud.PubSub.V1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BudgetTracker.Shared\BudgetTracker.Shared.csproj" />
    </ItemGroup>

</Project>
