// <auto-generated />
using System;
using BudgetTracker.Dues;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetTracker.Dues.Migrations
{
    [DbContext(typeof(WriteDBContext))]
    partial class WriteDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetTracker.Dues.Entities.Due", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comments")
                        .HasComment("Comments to describe each update action on due")
                        .HasAnnotation("Relational:JsonPropertyName", "comments");

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_date")
                        .HasAnnotation("Relational:JsonPropertyName", "completed_date");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Creditor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creditor")
                        .HasComment("Money is owed to this person")
                        .HasAnnotation("Relational:JsonPropertyName", "creditor");

                    b.Property<string>("Debtor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("debtor")
                        .HasComment("Person who owes money.")
                        .HasAnnotation("Relational:JsonPropertyName", "debtor");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComment("Description of what the Due is")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<decimal>("DueAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("due_amount")
                        .HasComment("Leftover due amount")
                        .HasAnnotation("Relational:JsonPropertyName", "due_amount");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remarks")
                        .HasComment("Additional info apert from description to describe the payment of the dues")
                        .HasAnnotation("Relational:JsonPropertyName", "remarks");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date")
                        .HasAnnotation("Relational:JsonPropertyName", "start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title")
                        .HasComment("Due short title")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount")
                        .HasComment("Total amount due to Creditor")
                        .HasAnnotation("Relational:JsonPropertyName", "total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.HasKey("Id");

                    b.ToTable("dues");
                });
#pragma warning restore 612, 618
        }
    }
}
